### ISSUE TITLE
Type Safety for URL options

### ISSUE THREAD

**Issue by danpalmer** [imgix/imgix-python#36]
There are many settings that can be used with Imgix. These have a range of types, but most are integers, floats, or strings that define an enumeration.

It would be great to get a more type-safe API using Python enums and/or mypy types. This would also give some basis to further safety in APIs provided using this library (such as a GraphQL API backed by this).

**Comment by jayeb** [comment]
Hi Dan, thanks for the ticket. Just to clarify, are you referring to `imgix-python` settings like `use_https` and `sign_key`, or are you referring to imgix URL parameters like `w` and `fm`?

**Comment by jayeb** [comment]
Ah, okay. We've considered this kind of augmentation to all of our SDK libraries in the past--being able to provide feedback to users when they accidentally set `w=blue` or `fm=yes` would be hugely helpful. This represents a fairly large undertaking to properly roll out across our entire stable of SDK libraries, though, and to be frank with you I don't think it's in the cards at the moment.

I do have some good news, though--the information you seek is already available. We have a small, probably-under-publicized library called [`imgix-url-params`](https://github.com/imgix/imgix-url-params) that exposes a JSON file describing the expected input values for all of our image API parameters. It's currently only published through NPM and Bower (since it was originally built for client-side purposes), but if you'd like to see the package exposed through another package manager we'd welcome a ticket or a PR to help with configuration.

Hope this helps! I'm going to close this ticket for now, but if you have further questions or ideas we're all ears.

**Comment by jayeb** [comment]
Yup, I'll put it on the to-do list.
